version: 0.0.{build}

branches:
  only:
    - master

clone_depth: 5
shallow_clone: false

image: Visual Studio 2017

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

install:
  - git submodule init
  - git submodule update  

build_script:
  - mkdir build
  - cd build 
  - cmake ../ -G "NMake Makefiles" -DXE_PLUGIN_OPENGLCORE=1
  - nmake
  - cd ..

test_script:
  - build/src/XE.Test/XE.Test
