version: 0.0.{build}

branches:
  only:
    - master

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

image: Visual Studio 2017

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - mkdir build
  - cd build 
  - cmake ../ -G "NMake Makefiles"
  - nmake
